### ISSUE TITLE
원본 파일을 컴파일 했을때 syntax error 발생

### ISSUE THREAD

**Issue by hansmee** [18-2-SKKU-OSS/2018-2-OSS-E1#2]
<img width="484" alt="2018-12-04 6 24 24" src="https://user-images.githubusercontent.com/29671099/49432061-2df55800-f7f2-11e8-8f4f-e00c82b59d32.png">

**Comment by UniqueEye** [comment]
프로젝트 주제를 다른 것으로 바꾸기로 결정함.
