### ISSUE TITLE
.js와 .css 파일에 Enter 키 처리가 제대로 되어있지 않아서 코드 분석에 어려움.

### ISSUE THREAD

**Issue by DormunDoorlock** [18-2-SKKU-OSS/2018-2-OSS-E1#3]
<img width="807" alt="kakaotalk_20181204_184253981" src="https://user-images.githubusercontent.com/43779340/49433158-a2c99180-f7f4-11e8-9390-6722fe05ab14.png">

**Comment by UniqueEye** [comment]
프로젝트 주제를 다른 것으로 바꾸기로 결정함.
