### ISSUE TITLE
각자 번역할 Section을 골라주세요.

### ISSUE THREAD

**Issue by UniqueEye** [18-2-SKKU-OSS/2018-2-OSS-E1#4]
1. Introduction ~ Usage
2. Section: Strain your brain!
3. Section: Appearances are deceptive!, Contributing ~ License
4. Section: Watch out for the landmines!

**Comment by UniqueEye** [comment]
3번

**Comment by DormunDoorlock** [comment]
4번 하겠습니다!!!!!!!!!!

**Comment by guswl98** [comment]
1번&2번 절반

**Comment by hansmee** [comment]
2번 절반
