### ISSUE TITLE
40 of HTML FIles

### ISSUE THREAD

**Issue by sam98528** [18-2-SKKU-OSS/2018-2-OSS-E1#5]
There are too many HTML Files, but we have to modify each of them. Therefore we need some way to make HTML easier and faster. one more thing is that, there are coding in the original readme.md file, so we have to think way to include the programing.

**Comment by UniqueEye** [comment]
How about importing them as image files?

**Comment by sam98528** [comment]
we separated the work into several parts, so that everyone can do something.
